---
title: "step 4 main code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(qwraps2)
library(olsrr)
library(haven)
library(tidyverse)
```


```{r}
load('data/rawdata.RData')
load('data/rawdata0.RData')
```


```{r}
# ***Figure 1: Consort diagram;
# proc contents data=B.rawdata0;
# run;
summary(rawdata)
```


```{r}
# data raw1;
# set B.rawdata0;
# COVID_year=year(COVID_diag_date);
# age=(covid_year-birth_yr);
# run;

raw1 <- rawdata0 %>% 
  rowwise() %>% 
  mutate(covid_year = as.numeric(format(`covid diag date`, "%Y")),
         age = covid_year - birth_yr
         )
```


```{r}
# data raw1_include;
# set raw1;
# where age>=18; 
# run;

raw1_include <- raw1 %>% 
  filter(age >= 18)
```

```{r}
# data raw1_exclude;
# set raw1;
# where age=. or age<18; 
# run;

raw1_exclude <- raw1 %>% 
  rowwise() %>% 
  filter(is.na(age) || age < 18)
```


##bug!!!!!! 
```{r}
# data raw2_include;
# set raw1_include;
# where COVID_diag_date>=cancer_date;                                            # missing treated as negative infinite
# run;


raw2_include <- raw1_include %>%
  # if not use rowwise, will have error
  rowwise() %>%  
  filter(is.na(cancer_date) || (`covid diag date` >= cancer_date ))
```



```{r}
# proc freq data=raw2_include;
# tables cancer;
# run;

proc_freq(raw2_include, c('cancer'))
```


```{r}
# ***Table 1 and 2;
# data rawdata;
# set B.rawdata;
# if gender="Unknown" then gender="z: Unknown"; *rename to make this category appear in the last row;
# if age_cancer_gp="miss" then age_cancer_gp="z: Unknown";
# if age_gp="" then age_gp="z: Unknown";
# if obese_overweight="" then obese_overweight="z: Unknown";
# if Surgery_4w=1 then surgery4wk="Yes";
# else if Surgery_4w=0 then surgery4wk="No";
# else if Surgery_4w=. then surgery4wk="z: Unknown";
# run;

rawdata <- rawdata %>% 
  rowwise() %>% 
  mutate(gender = ifelse(gender == 'Unknown', 'z: Unknown', gender),
         age_cancer_gp = ifelse(age_cancer_gp == 'miss', 'z: Unknown', age_cancer_gp),
         age_gp= ifelse(is.na(age_gp), 'z: Unknown', age_gp),
         obese_overweight = ifelse(is.na(obese_overweight), 'z: Unknown', obese_overweight),
         surgery4wk = ifelse(is.na(surgery_4w), 'z: Unknown', 
                             ifelse(surgery_4w == 1 , "Yes",
                             ifelse(surgery_4w == 0, 'No', NA)))
         )
         
```


```{r}
# proc datasets; delete S0-S20; run;
# %twoway_digital_Outcome(rawdata,cancer, 0,1,death,1 );
# %twoway_digital_Outcome(rawdata,cancer, 0,1,Inpatient,2 );
# %twoway_digital_Outcome(rawdata,cancer, 0,1,ICU,3);
# %twoway_digital_Outcome(rawdata,cancer, 0,1,Ventilation,4);
# %twoway_digital_Outcome(rawdata,cancer, 0,1,severity,5);
# %twoway_digital_Outcome(rawdata,cancer, 0,1,severity_level,6);
# 
# *independent variables;
# %twoway_nominal(rawdata, cancer, 0,1, age_gp,7);
# %twoway_nominal(rawdata,cancer, 0,1,gender,8);
# %twoway_nominal(rawdata,cancer, 0,1,race_gp,9);
# %twoway_nominal(rawdata,cancer, 0,1,Region,10);
# %twoway_nominal(rawdata,cancer, 0,1,N_comorbity_gp,11);
# %twoway_nominal(rawdata,cancer, 0,1,N_Posi_Comorb_gp,12);
# %twoway_nominal(rawdata,cancer, 0,1,surgery4wk,13);
# %twoway_nominal(rawdata,cancer, 0,1,cancer_type,14);
# %twoway_digital(rawdata,cancer, 0,1,chemo_4w,15);
# %twoway_digital(rawdata,cancer, 0,1,Radiation_4w,16);
# %twoway_nominal(rawdata,cancer, 0,1,age_cancer_gp,17);
# %twoway_digital(rawdata,cancer, 0,1,survive_5yr_more,18);
  
```

```{r}
table(rawdata$death, rawdata$cancer, useNA = 'no')
```


```{r}
options(qwraps2_markup = "markdown")

table_data <- rawdata %>% 
  select(death, cancer) %>% 
  group_by(cancer)
  
our_summary1 <-
  list("death, n(%)" =
        list("0" = ~ qwraps2::n_perc0(death == 0),
            "1"  = ~ qwraps2::n_perc0(death == 1))
  )

summary_table(table_data, our_summary1)

```

```{r}

```




```{r}
# data alltime;
# set B.rawdata;
# keep cancer T_30 death;
# run;
# PROC EXPORT DATA= WORK.alltime  
#             OUTFILE= "Z:\8 GQ Zhang group\STEP1 data analysis\alltime.csv" 
#             DBMS=CSV REPLACE;
#      PUTNAMES=YES;
# RUN;
#  
# data matched_data;
# set matched;
# keep cancer T_30  death;
# run;
# PROC EXPORT DATA= WORK.matched_data  
#             OUTFILE= "Z:\8 GQ Zhang group\STEP1 data analysis\matched_data.csv" 
#             DBMS=CSV REPLACE;
#      PUTNAMES=YES;
# RUN;
```

```{r}
# proc logistic data=rawdata_cancer descending;
# class  age_gp(ref=first) gender(ref=first)    race_gp(ref="Non-hispanic white")
# Surgery_4w(ref=first)  cancer_type(ref=first)
# survive_5yr_more(ref=first)
# Radiation_4w(ref=first) chemo_4w(ref=first)
# / param=ref;
# model severity=age_gp gender  
# race_gp
# N_comorbity
# N_Posi_Comorb
# Surgery_4w
# cancer_type
# chemo_4w
# Radiation_4w 
# survive_5yr_more/selection=stepwise;
# ods output ParameterEstimates=Prob(where=(Variable~='Intercept') keep=
# variable ProbChiSq) OddsRatios=OR(keep=effect OddsRatioEst 
# LowerCL UpperCL);
# run;


# fit <- glm(severity ~ age_gp + gender + race_gp + n_comorbity + n_posi_comorb +
#              surgery_4w + cancer_type + chemo_4w +radiation_4w + survive_5yr_more,
#           family = binomial(), data = rawdata)
# 
# ols_step_both_p(fit, pent = 0.1, prem = 0.3, details = TRUE)
```









# the following code is used to test equality of the data generated by R and SAS
```{r}
dat <- read_sas('data/rawdata.sas7bdat')
```

```{r}
colnames(dat) <- tolower(colnames(dat))
```

```{r}
dat <- dat %>% select(-c("p85", "p90", "p95", "p97"))
```

```{r}
nrow(dat[, 1])
```

```{r}
colname <- colnames(rawdata)
for(i in 1:ncol(dat)) {
  print(colname[i])
  print(all(match(dat[, i], rawdata[, i]) == 1))
}
```

```{r}
dat[dat == ''] <- NA
```


```{r}
# dat <- dat %>% mutate(smoke = ifelse(is.na(smoke), NA, smoke))
all(dat[!is.na(dat$smoke_by_icd_group), ]$smoke_by_icd_group == rawdata[!is.na(rawdata$smoke_by_icd_group), ]$smoke_by_icd_group)
```
```


```{r}
colnames(rawdata)
```

```{r}
colnames(dat)
```

